-- Phase 1, contract v1.1. Generated by Prisma 7.10; qualified and extended below.
BEGIN;
SET LOCAL search_path = pg_catalog, public;
SET LOCAL lock_timeout = '10s';

-- CreateSchema
CREATE SCHEMA IF NOT EXISTS "public";

-- CreateEnum
CREATE TYPE "public"."user_status" AS ENUM ('ACTIVE', 'BLOCKED', 'DELETED');

-- CreateEnum
CREATE TYPE "public"."restaurant_status" AS ENUM ('ACTIVE', 'INACTIVE', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "public"."location_status" AS ENUM ('ACTIVE', 'INACTIVE', 'ARCHIVED');

-- CreateEnum
CREATE TYPE "public"."merchant_role" AS ENUM ('OWNER', 'ADMIN', 'MANAGER', 'STAFF', 'ANALYST');

-- CreateEnum
CREATE TYPE "public"."membership_status" AS ENUM ('INVITED', 'ACTIVE', 'SUSPENDED', 'REVOKED');

-- CreateEnum
CREATE TYPE "public"."membership_scope_type" AS ENUM ('ALL_LOCATIONS', 'SELECTED_LOCATIONS');

-- CreateTable
CREATE TABLE "public"."users" (
    "id" UUID NOT NULL,
    "display_name" VARCHAR(100) NOT NULL,
    "avatar_url" TEXT,
    "date_of_birth" DATE,
    "locale" VARCHAR(10) NOT NULL,
    "time_zone" VARCHAR(50) NOT NULL,
    "status" "public"."user_status" NOT NULL,
    "marketing_consent_at" TIMESTAMPTZ(6),
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "deleted_at" TIMESTAMPTZ(6),

    CONSTRAINT "users_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."restaurants" (
    "id" UUID NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "slug" VARCHAR(120) NOT NULL,
    "legal_name" VARCHAR(160),
    "tax_id" VARCHAR(40),
    "website_url" TEXT,
    "status" "public"."restaurant_status" NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "restaurants_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."restaurant_locations" (
    "id" UUID NOT NULL,
    "restaurant_id" UUID NOT NULL,
    "name" VARCHAR(120) NOT NULL,
    "slug" VARCHAR(120) NOT NULL,
    "address_line_1" VARCHAR(160) NOT NULL,
    "address_line_2" VARCHAR(160),
    "city" VARCHAR(100) NOT NULL,
    "region" VARCHAR(100) NOT NULL,
    "postal_code" VARCHAR(20),
    "country_code" CHAR(2) NOT NULL,
    "latitude" DECIMAL(9,6),
    "longitude" DECIMAL(9,6),
    "time_zone" VARCHAR(50) NOT NULL,
    "phone" VARCHAR(30),
    "status" "public"."location_status" NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "restaurant_locations_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."merchant_memberships" (
    "id" UUID NOT NULL,
    "user_id" UUID NOT NULL,
    "restaurant_id" UUID NOT NULL,
    "role" "public"."merchant_role" NOT NULL,
    "status" "public"."membership_status" NOT NULL,
    "created_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "scope_type" "public"."membership_scope_type" NOT NULL,
    "invited_by_user_id" UUID,
    "invited_at" TIMESTAMPTZ(6) NOT NULL,
    "accepted_at" TIMESTAMPTZ(6),

    CONSTRAINT "merchant_memberships_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."merchant_membership_locations" (
    "membership_id" UUID NOT NULL,
    "location_id" UUID NOT NULL,

    CONSTRAINT "merchant_membership_locations_pkey" PRIMARY KEY ("membership_id","location_id")
);

-- CreateIndex
CREATE UNIQUE INDEX "restaurants_slug_key" ON "public"."restaurants"("slug");

-- CreateIndex
CREATE UNIQUE INDEX "restaurant_locations_restaurant_id_slug_key" ON "public"."restaurant_locations"("restaurant_id", "slug");

-- CreateIndex
CREATE INDEX "merchant_memberships_restaurant_id_status_idx" ON "public"."merchant_memberships"("restaurant_id", "status");

-- CreateIndex
CREATE UNIQUE INDEX "merchant_memberships_user_id_restaurant_id_key" ON "public"."merchant_memberships"("user_id", "restaurant_id");

-- CreateIndex
CREATE INDEX "merchant_membership_locations_location_id_membership_id_idx" ON "public"."merchant_membership_locations"("location_id", "membership_id");

-- AddForeignKey
ALTER TABLE "public"."restaurant_locations" ADD CONSTRAINT "restaurant_locations_restaurant_id_fkey" FOREIGN KEY ("restaurant_id") REFERENCES "public"."restaurants"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "public"."merchant_memberships" ADD CONSTRAINT "merchant_memberships_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "public"."merchant_memberships" ADD CONSTRAINT "merchant_memberships_restaurant_id_fkey" FOREIGN KEY ("restaurant_id") REFERENCES "public"."restaurants"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "public"."merchant_memberships" ADD CONSTRAINT "merchant_memberships_invited_by_user_id_fkey" FOREIGN KEY ("invited_by_user_id") REFERENCES "public"."users"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "public"."merchant_membership_locations" ADD CONSTRAINT "merchant_membership_locations_membership_id_fkey" FOREIGN KEY ("membership_id") REFERENCES "public"."merchant_memberships"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- AddForeignKey
ALTER TABLE "public"."merchant_membership_locations" ADD CONSTRAINT "merchant_membership_locations_location_id_fkey" FOREIGN KEY ("location_id") REFERENCES "public"."restaurant_locations"("id") ON DELETE RESTRICT ON UPDATE RESTRICT;

-- Controlled cross-schema reference: only public is altered. Supabase owns Auth.
-- Immediate by default; explicit deferral permits rollback-only integration fixtures.
-- RESTRICT still prevents deleting/updating a referenced Auth identity immediately.
ALTER TABLE public.users ADD CONSTRAINT users_auth_user_fkey
  FOREIGN KEY (id) REFERENCES auth.users(id)
  ON DELETE RESTRICT ON UPDATE RESTRICT DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE public.merchant_memberships
  ADD CONSTRAINT merchant_memberships_active_accepted_check
  CHECK (status <> 'ACTIVE' OR accepted_at IS NOT NULL);

-- SQL writes, including association changes, also maintain server-side audit time.
CREATE FUNCTION public.set_updated_at() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
BEGIN
  NEW.updated_at := clock_timestamp();
  RETURN NEW;
END;
$$;

CREATE TRIGGER users_updated_at BEFORE UPDATE ON public.users
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER restaurants_updated_at BEFORE UPDATE ON public.restaurants
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER restaurant_locations_updated_at BEFORE UPDATE ON public.restaurant_locations
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();
CREATE TRIGGER merchant_memberships_updated_at BEFORE UPDATE ON public.merchant_memberships
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE FUNCTION public.enforce_membership_identity() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
BEGIN
  IF NEW.user_id IS DISTINCT FROM OLD.user_id
     OR NEW.restaurant_id IS DISTINCT FROM OLD.restaurant_id THEN
    RAISE EXCEPTION 'Membership user and restaurant are immutable'
      USING ERRCODE = '23514', CONSTRAINT = 'merchant_memberships_identity_check';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER merchant_memberships_identity
  BEFORE UPDATE OF user_id, restaurant_id ON public.merchant_memberships
  FOR EACH ROW EXECUTE FUNCTION public.enforce_membership_identity();

-- Freeze location ownership so reassignment cannot invalidate selections/history.
CREATE FUNCTION public.enforce_location_restaurant() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
BEGIN
  IF NEW.restaurant_id IS DISTINCT FROM OLD.restaurant_id THEN
    RAISE EXCEPTION 'Location restaurant is immutable'
      USING ERRCODE = '23514', CONSTRAINT = 'restaurant_locations_restaurant_immutable_check';
  END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER restaurant_locations_restaurant_immutable
  BEFORE UPDATE OF restaurant_id ON public.restaurant_locations
  FOR EACH ROW EXECUTE FUNCTION public.enforce_location_restaurant();

-- Serialize all association mutations through the owner, including direct SQL.
-- An actual UPDATE (not just a row lock) also prevents stale-snapshot write skew
-- under REPEATABLE READ: competing transactions must retry SQLSTATE 40001.
-- Callers modifying multiple memberships must lock owners in UUID order FIRST,
-- before touching association rows; row-trigger fallback may otherwise deadlock
-- (40P01, retry whole transaction), but cannot commit an invalid selection.
CREATE FUNCTION public.lock_membership_selection() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
DECLARE
  owner_ids uuid[] := ARRAY[]::uuid[];
  owner_id uuid;
BEGIN
  IF TG_OP <> 'INSERT' THEN
    owner_ids := array_append(owner_ids, OLD.membership_id);
  END IF;
  IF TG_OP <> 'DELETE' THEN
    owner_ids := array_append(owner_ids, NEW.membership_id);
  END IF;
  FOR owner_id IN SELECT DISTINCT id FROM unnest(owner_ids) AS owners(id) ORDER BY id LOOP
    UPDATE public.merchant_memberships SET updated_at = clock_timestamp() WHERE id = owner_id;
  END LOOP;
  IF TG_OP = 'DELETE' THEN RETURN OLD; END IF;
  RETURN NEW;
END;
$$;

CREATE TRIGGER merchant_membership_locations_lock
  BEFORE INSERT OR UPDATE OR DELETE ON public.merchant_membership_locations
  FOR EACH ROW EXECUTE FUNCTION public.lock_membership_selection();

-- Check final state, not transition rows captured earlier in the transaction.
-- Both ends and both OLD/NEW membership IDs are covered, including moves/deletes.
CREATE FUNCTION public.enforce_membership_scope() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
DECLARE
  owner_ids uuid[] := ARRAY[]::uuid[];
  owner_id uuid;
  owner_restaurant uuid;
  owner_scope public.membership_scope_type;
  has_locations boolean;
BEGIN
  IF TG_TABLE_NAME = 'merchant_memberships' THEN
    IF TG_OP <> 'INSERT' THEN owner_ids := array_append(owner_ids, OLD.id); END IF;
    IF TG_OP <> 'DELETE' THEN owner_ids := array_append(owner_ids, NEW.id); END IF;
  ELSE
    IF TG_OP <> 'INSERT' THEN owner_ids := array_append(owner_ids, OLD.membership_id); END IF;
    IF TG_OP <> 'DELETE' THEN owner_ids := array_append(owner_ids, NEW.membership_id); END IF;
  END IF;

  FOR owner_id IN SELECT DISTINCT id FROM unnest(owner_ids) AS owners(id) ORDER BY id LOOP
    SELECT restaurant_id, scope_type INTO owner_restaurant, owner_scope
      FROM public.merchant_memberships WHERE id = owner_id;
    IF NOT FOUND THEN CONTINUE; END IF;

    SELECT EXISTS (SELECT 1 FROM public.merchant_membership_locations WHERE membership_id = owner_id)
      INTO has_locations;
    IF (owner_scope = 'ALL_LOCATIONS' AND has_locations)
       OR (owner_scope = 'SELECTED_LOCATIONS' AND NOT has_locations) THEN
      RAISE EXCEPTION 'Membership selection does not match scope_type'
        USING ERRCODE = '23514', CONSTRAINT = 'merchant_memberships_scope_check';
    END IF;

    IF EXISTS (
      SELECT 1 FROM public.merchant_membership_locations AS selection
      JOIN public.restaurant_locations AS location ON location.id = selection.location_id
      WHERE selection.membership_id = owner_id AND location.restaurant_id <> owner_restaurant
    ) THEN
      RAISE EXCEPTION 'Selected location belongs to another restaurant'
        USING ERRCODE = '23514', CONSTRAINT = 'merchant_membership_locations_restaurant_check';
    END IF;
  END LOOP;
  RETURN NULL;
END;
$$;

CREATE CONSTRAINT TRIGGER merchant_memberships_scope
  AFTER INSERT OR UPDATE OR DELETE ON public.merchant_memberships
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.enforce_membership_scope();

CREATE CONSTRAINT TRIGGER merchant_membership_locations_scope
  AFTER INSERT OR UPDATE OR DELETE ON public.merchant_membership_locations
  DEFERRABLE INITIALLY DEFERRED
  FOR EACH ROW EXECUTE FUNCTION public.enforce_membership_scope();

-- TRUNCATE does not fire row triggers and could leave selected memberships empty.
CREATE FUNCTION public.prevent_selection_truncate() RETURNS trigger
LANGUAGE plpgsql SECURITY INVOKER SET search_path = pg_catalog AS $$
BEGIN
  RAISE EXCEPTION 'Use transactional DELETE for membership selections'
    USING ERRCODE = '0A000';
END;
$$;

CREATE TRIGGER merchant_membership_locations_no_truncate
  BEFORE TRUNCATE ON public.merchant_membership_locations
  FOR EACH STATEMENT EXECUTE FUNCTION public.prevent_selection_truncate();

-- No client access policies yet. Business writes will go through NestJS.
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurants ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.restaurant_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.merchant_memberships ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.merchant_membership_locations ENABLE ROW LEVEL SECURITY;

-- Prisma creates its bookkeeping table before running migrations. Protect it
-- from the Data API as well; it is not an application model.
DO $$
BEGIN
  IF to_regclass('public._prisma_migrations') IS NOT NULL THEN
    ALTER TABLE public._prisma_migrations ENABLE ROW LEVEL SECURITY;
  END IF;
END;
$$;

-- Trigger helpers are internal, never public RPC endpoints.
REVOKE ALL ON FUNCTION public.set_updated_at() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.enforce_membership_identity() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.enforce_location_restaurant() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.lock_membership_selection() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.enforce_membership_scope() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.prevent_selection_truncate() FROM PUBLIC, anon, authenticated;

COMMIT;
